import "bootstrap/dist/css/bootstrap.min.css"; // JS (dropdown, offcanvas, modal...)
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import BootstrapClient from "@/components/BootstrapClient";
import StoreProvider from "./StoreProvider";
import Script from "next/script";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/scrollbar";
import { AuthInitializer } from "@/components/auth/AuthInitializer";
import { useEffect } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en" className="mdl-js">
        <head>
          <link rel="stylesheet" href="/assets/css/main.css" />
          <link
            href="/assets/vendor/bootstrap/css/bootstrap.min.css"
            rel="stylesheet"
          />
          <link
            href="/assets/vendor/bootstrap-icons/bootstrap-icons.css"
            rel="stylesheet"
          />
          <link href="/assets/vendor/aos/aos.css" rel="stylesheet" />
          <link
            href="/assets/vendor/glightbox/css/glightbox.min.css"
            rel="stylesheet"
          />
          <link
            href="/assets/vendor/swiper/swiper-bundle.min.css"
            rel="stylesheet"
          />
        </head>
        <body className={`index-page`}>
          <main className="main">
            <BootstrapClient />
            {children}
          </main>

          <Script src="/assets/js/main.js" strategy="afterInteractive" />
        </body>
      </html>
    </StoreProvider>
  );
}
