spring.application.name=Thoai-pro-spring


	
sqlserver.host=103.118.28.72
sqlserver.port=1433
sqlserver.database=ProductDB
sqlserver.username=sa
sqlserver.password=Thoai150396

spring.data.redis.host=103.118.28.72
spring.data.redis.port=6379
spring.data.redis.password=Thoai150396
# Add password if your server requires authentication
# spring.data.redis.password=your_secure_password 


#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
#vnpay.tmnCode=Q5JM2QKZ
#vnpay.hashSecret=LWRKY549FJ1BU3V0JKOB31Y0HLTXMXMA
vnpay.tmnCode=WK7FXXYK
vnpay.hashSecret=67KQXGHU4ULJWQLBV1I7RX3JWSO2C7KE
vnpay.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
#vnpay.returnUrl=http://localhost:8000/payment/vnpay_return
vnpay.returnUrl=http://localhost:8004/payment/vnpay_return
file.upload-dir=uploads
server.port=8004	